# Generated by Django 4.2.13 on 2024-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apartment Cleaning(Wednesday)',
                'verbose_name_plural': 'Apartment Cleaning(Wednesday)',
            },
        ),
        migrations.CreateModel(
            name='DryStorageCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dry Storage Cleaning(Wednesday)',
                'verbose_name_plural': 'Dry Storage Cleaning(Wednesday)',
            },
        ),
        migrations.CreateModel(
            name='KitchenLate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pizza_grade', models.IntegerField()),
                ('tomorrow_balls_total', models.IntegerField()),
                ('old_balls_total', models.IntegerField()),
                ('balls_broken_today', models.IntegerField()),
                ('pizzas_broken_today', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kitchen Department Late Shift(Quantity)',
                'verbose_name_plural': 'Kitchen Department Late Shift(Quantity)',
            },
        ),
        migrations.CreateModel(
            name='KitchenLateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default=False, max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('soap_WC_sufficient', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
                ('toilet_paper_WC_sufficient', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
                ('grease_remover_kitchen_sufficient', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
                ('washingup_liquid_kitchen_sufficient', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
                ('blue_roll_kitchen_sufficient', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen Department Late Shift(Task)',
                'verbose_name_plural': 'Kitchen Department Late Shift(Task)',
            },
        ),
        migrations.CreateModel(
            name='KitchenLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('today_balls_total', models.IntegerField()),
                ('yesterday_balls_total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kitchen Department Lunch Shift(Quantity)',
                'verbose_name_plural': 'Kitchen Department Lunch Shift(Quantity)',
            },
        ),
        migrations.CreateModel(
            name='KitchenLunchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('task_kitchen_cleaned', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True, verbose_name='Kitchen cleaned according to instructions')),
                ('task_enough_laundry', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True, verbose_name='Was there enough laundry')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen Department Lunch Shift(Task)',
                'verbose_name_plural': 'Kitchen Department Lunch Shift(Task)',
            },
        ),
        migrations.CreateModel(
            name='KitchenSpecialcleaningMonday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen Department Specialcleaning(Monday)',
                'verbose_name_plural': 'Kitchen Department Specialcleaning(Monday)',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalLate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('hallway_mopped', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
                ('cellar_tidy', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
                ('replenished', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Terminal Department Late Shift',
                'verbose_name_plural': 'Terminal Department Late Shift',
            },
        ),
        migrations.CreateModel(
            name='TerminalLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Terminal Department Lunch Shift',
                'verbose_name_plural': 'Terminal Department Lunch Shift',
            },
        ),
        migrations.CreateModel(
            name='WednesdayCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen Special Cleaning(Wednesday)',
                'verbose_name_plural': 'Kitchen Special Cleaning(Wednesday)',
            },
        ),
    ]
